### ISSUE TITLE
Unhandled exception in interactive mode

### ISSUE THREAD

**Issue by nomardt** [nomardt/OpenAI-Search#13]
![Screenshot at 2023-01-17 09-23-03](https://user-images.githubusercontent.com/115152912/212824960-525e8f1b-0f0e-422e-90f1-47ebd928a135.png)

**Comment by LagrangeH** [comment]
Please leave a traceback with a text, not a picture, don't cringe, @nomardt

**Comment by LagrangeH** [comment]
I got this, so I think the issue can be closed.

```
> 100 random common words in spanish and their translation
1. Hola - Hello
2. Adiós - Goodbye
3. Por favor - Please
4. Gracias - Thank you
5. Sí - Yes
...
96. Hora - Hour
97. Minuto - Minute
98. Segundo - Second
99. Semana - Week
100. Mes - Month
```
