### ISSUE TITLE
WTF

### ISSUE THREAD

**Issue by nomardt** [nomardt/OpenAI-Search#14]
![Screenshot at 2023-01-19 01-22-47](https://user-images.githubusercontent.com/115152912/213308457-d460aa9d-dd83-45ff-b7ca-f157a80ab9a8.png)
He doesn't breathe!!!

**Comment by LagrangeH** [comment]
I cannot repeat this case. What was your prompt?

**Comment by nomardt** [comment]
It is a character with some very unique encoding, I can't repeat it either.
