### ISSUE TITLE
Don't think there should be Process finished in such cases....

### ISSUE THREAD

**Issue by nomardt** [nomardt/OpenAI-Search#29]
![Screenshot at 2023-01-30 13-26-11](https://user-images.githubusercontent.com/115152912/215452186-acfde0f0-d5c7-42b9-a89a-1b844263c17c.png)

...because ais is always moving forward and it cannot be finished!

**Comment by LagrangeH** [comment]
This is the same issue as #15. Is not it?

**Comment by LagrangeH** [comment]
@nomardt, why...?
